"""add ors_profile to vehicle_types

Revision ID: 4322c2a386d4
Revises: 108be392ad9d
Create Date: 2026-03-12 10:22:46.301301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4322c2a386d4'
down_revision: Union[str, Sequence[str], None] = '108be392ad9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_types', sa.Column('ors_profile', sa.String(length=20), nullable=False))
    op.alter_column('vehicle_types', 'name',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vehicle_types', 'name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
    op.drop_column('vehicle_types', 'ors_profile')
    # ### end Alembic commands ###
