"""add current_warehouse_id to vehicles

Revision ID: 6cdc9b74b0f6
Revises: af8bcbc50e97
Create Date: 2026-03-15 12:51:46.148951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cdc9b74b0f6'
down_revision: Union[str, Sequence[str], None] = 'af8bcbc50e97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('current_warehouse_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'vehicles', 'warehouses', ['current_warehouse_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'current_warehouse_id')
    # ### end Alembic commands ###
